development:
  GOOGLE_CLOUD_KEY: <key to access Google web APIs>
  SESSION_SECRET: <some secret>
  REDISCLOUD_URL: <url assigned by Redis provider on Heroku>
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  ADDITION_QUEUE: youtubetrendingmap-development
  ADDITION_QUEUE_URL: <set by AWS>

test:
  GOOGLE_CLOUD_KEY: <key to access Google web APIs>
  SESSION_SECRET: <some secret>
  REDISCLOUD_URL: <url assigned by Redis provider on Heroku>
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  ADDITION_QUEUE: youtubetrendingmap-development
  ADDITION_QUEUE_URL: <set by AWS>

production:
  GOOGLE_CLOUD_KEY: <key to access Google web APIs>
  SESSION_SECRET: <some secret>
  REDISCLOUD_URL: <url assigned by Redis provider on Heroku>
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  ADDITION_QUEUE: youtubetrendingmap-development
  ADDITION_QUEUE_URL: <set by AWS>
