development:
  GOOGLE_CLOUD_KEY: <key to access Google web APIs>
  SESSION_SECRET: <some secret>
  REDISCLOUD_URL: <url assigned by Redis provider on Heroku>

test:
  GOOGLE_CLOUD_KEY: <key to access Google web APIs>
  SESSION_SECRET: <some secret>
  REDISCLOUD_URL: <url assigned by Redis provider on Heroku>

production:
  GOOGLE_CLOUD_KEY: <key to access Google web APIs>
  SESSION_SECRET: <some secret>
  REDISCLOUD_URL: <url assigned by Redis provider on Heroku>
