development:
  GOOGLE_CLOUD_KEY: <key to access Google web APIs>
  SESSION_SECRET: <some secret>

test:
  GOOGLE_CLOUD_KEY: <key to access Google web APIs>
  SESSION_SECRET: <some secret>

production:
  GOOGLE_CLOUD_KEY: <key to access Google web APIs>
  SESSION_SECRET: <some secret>
